//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Userssssssss
{
    using System;
    using System.Collections.Generic;

    public partial class Userss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Userss()
        {
            this.Role = new HashSet<Role>();
        }

        public int idUser { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public int idGender { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int idRole { get; set; }

        public string FI { get => $"{LName} {FName}"; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role { get; set; }
    }
}
